apiVersion: v1
kind: Namespace
metadata:
  name: home-assistent
---
apiVersion: argoproj.io/v1alpha1
kind: Project
metadata:
  name: home-assistent
  namespace: argocd
spec:
  description: Project for Home Assistant
  sourceRepos:
    - '*'
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: home-assistent
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - group: '*'
      kind: 'Pod'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistent
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: homeassistant/home-assistant:latest
          ports:
            - containerPort: 8123
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-config
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistent
spec:
  selector:
    app: home-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8123
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: home-assistent
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant-ingress
  namespace: home-assistent
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: home-assistant.rancher.hro.dev.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 80
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn
spec:
  provisioner: driver.longhorn.io
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant-app
  namespace: argocd
spec:
  project: home-assistent
  source:
    repoURL: 'https://github.com/hroliveira/home-assistant-k8s.git'
    targetRevision: HEAD
    path: 'k8s-configs'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: home-assistent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
